### PR TITLE
added missing office types to extension mime type map

### PR DESCRIPTION
**Pull request by alperenersoy**
hey! we have just started to use your package. thanks for that. in this pr just added some missing mime types for microsoft office extensions.

### CODE REVIEW

**Review by martincivan — APPROVED** [review]

**Comment by martincivan** [comment]
@alperenersoy thank you for your contribution, released in `1.2.6`

**Comment by alperenersoy** [comment]
@martincivan thanks! as i see the jpegs are mapped as `image/pjpeg`. are there any specific reasons for it instead of using `image/jpeg`?

**Comment by martincivan** [comment]
@alperenersoy I have no idea... this is how it was in the original Squirellmail plugin that I extracted the logic from.

**Comment by martincivan** [comment]
perhaps there exists some library that has these file-extension <> mime-type data more complete / in better shape, I haven't looked into it as I didn't notice any problem with this in our use-case.

**Comment by alperenersoy** [comment]
@martincivan in https://github.com/QualityUnit/TNEFDecoder/pull/19 replaced them with generic `image/jpeg`. and added some mime types for [common extensions](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types).

**Pull request merged**
